name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - run: go build -o macadmin
    - run: go test -race -covermode=atomic -shuffle=on -coverprofile=coverage.out

    - uses: paambaati/codeclimate-action@v4
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        prefix: 'github.com/brokeyourbike/macadmin'
        coverageLocations: ./coverage.out:gocov
